### ISSUE TITLE
Type Error: __init__() got an unexpected keyword argument 'epochs'

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#26] opened 2021-09-01 12:11 UTC
![1](https://user-images.githubusercontent.com/26819449/131668023-b906eed7-fc52-43f0-996a-5e6f91fcbdfb.JPG)
![2](https://user-images.githubusercontent.com/26819449/131668037-5f770ae3-4b13-4f07-a2af-32230f88439b.JPG)
![3](https://user-images.githubusercontent.com/26819449/131668041-11f9910d-cc88-431c-8968-b57a7ebb9880.JPG)
![4](https://user-images.githubusercontent.com/26819449/131668056-c1838e40-6761-4735-af7d-1f45f48ca681.JPG)
hello,
Is this a bug?
Please tell me how can I solve it?
It would be helpful if you also let me know which documentation to refer to.
Thank you.

**Comment by wkopp** [comment] 2021-09-02 07:49
No, it's not a bug. There is no epochs argument for ReduceDim. You got your closing parentheses wrong.

**Closed by wkopp** 2021-09-02 07:49 UTC
