### ISSUE TITLE
Classify_nucleotide_sequences

### ISSUE THREAD

**Issue by eallen4040** [BIMSBbioinfo/janggu#15] opened 2020-09-29 04:00 UTC
Hello!

I am relatively new to the world of neural networks! I've been in contact with this group before and you all have been a tremendous help! I am currently attempting to run the examples available in jupyter notebook. I specifically want to ask about Classify_nucleotide_sequences. I have a couple errors return when I run the first cell:

ImportError                               Traceback (most recent call last)
<ipython-input-1-4b9fed5d2166> in <module>
      9 from keras.layers import Maximum
     10 
---> 11 from janggu import Janggu
     12 from janggu import Scorer
     13 from janggu import inputlayer

~/anaconda3/envs/janggu/lib/python3.6/site-packages/janggu/__init__.py in <module>
      4 from janggu.decorators import outputconv  # noqa
      5 from janggu.decorators import outputdense  # noqa
----> 6 from janggu.evaluation import Scorer  # noqa
      7 from janggu.layers import Complement  # noqa
      8 from janggu.layers import DnaConv2D  # noqa

~/anaconda3/envs/janggu/lib/python3.6/site-packages/janggu/evaluation.py in <module>
     18 from sklearn.metrics import roc_curve
     19 
---> 20 from janggu.utils import ExportJson
     21 from janggu.utils import ExportScorePlot
     22 from janggu.utils import ExportTsv

~/anaconda3/envs/janggu/lib/python3.6/site-packages/janggu/utils.py in <module>
     10 import pandas as pd
     11 from Bio import SeqIO
---> 12 from Bio.Alphabet import IUPAC
     13 from Bio.Seq import Seq
     14 from Bio.SeqRecord import SeqRecord

~/anaconda3/envs/janggu/lib/python3.6/site-packages/Bio/Alphabet/__init__.py in <module>
     19 
     20 raise ImportError(
---> 21     "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
     22 )

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Can I get a little insight on these errors and how to fix them? I would really appreciate it!

**Comment by wkopp** [comment] 2020-09-29 08:47
Hi @eallen4040,

The issue use caused by an update in the package `Biopython==1.78`.
Install Biopython==1.77 with `pip install biopython==1.77`. This should resolve the issue.

I've adjusted setup.py such that it requires Biopython==1.77. This is available in the github master branch and will be part of the new version soon.

Best,
Wolfgang

**Closed** 2020-09-29 15:36 UTC
